services:
  react:
    build: frontend
    volumes:
      - "./frontend/src:/app/src"
      - "./frontend/package.json:/app/package.json"
      - "./frontend/yarn.lock:/app/yarn.lock"
    ports:
      - 3000:3000
  web:
    build: backend
    volumes:
      - "./backend:/app"
    ports:
      - 5000:5000
