version: "3.7"
services:
  web:
    build: backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cn7vlDky584Lo3rk
      - POSTGRES_DB=postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.startmetrics.sgmakarov.ru`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=5000"
    extra_hosts:
      - 'db:34.89.182.168'
    networks:
      - proxy

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`startmetrics.sgmakarov.ru`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=letsencrypt"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    networks:
      - proxy  

networks:
  proxy:
    external:
      name: 'public'