version: "3.7"
services:
  react:
    build: frontend
    volumes:
      - "./frontend/src:/app/src"
      - "./frontend/package.json:/app/package.json"
      - "./frontend/yarn.lock:/app/yarn.lock"
    ports:
      - 3000:3000
  web:
    build: backend
    volumes:
      - "./backend:/app"
    ports:
      - 5000:5000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cn7vlDky584Lo3rk
      - POSTGRES_DB=postgres
    extra_hosts:
      - 'db:34.89.182.168'

